### ISSUE TITLE
Show record types as text instead of Id value

### ISSUE THREAD

**Issue by stevebuik** [stevebuik/Graphvizforce-Lightning#13]
suggested by a user in Germany

**Comment by austinwang1121** [comment]
Hi Steve, this seems like an easy one to start with, can I take it?

**Comment by stevebuik** [comment]
Hi Austin, by all means have a try. I just tried to reproduce this but
could not so you might just be able to test it more and confirm it's ok.

I've just done a lot of work on the tool and it's now ready for testing.
I've attached a video for your viewing pleasure.

Jason is pretty slammed wth the FACS release right now. He might be willing
to let you take over the appexchange packaging work. Jason, what do you
think?

Regards, Steve Buikhuizen

http://www.linkedin.com/in/stevebuikhuizen

Mob: +61 416 426 414

**Comment by stevebuik** [comment]
I just tested more, this is not a bug any more so I'll close it. Austin there are plenty more you can do if you are interested.

**Comment by austinwang1121** [comment]
Sure. Will pick another one
