### ISSUE TITLE
Master-Detail relationships not showing as solid lines

### ISSUE THREAD

**Issue by stevebuik** [stevebuik/Graphvizforce-Lightning#27]
in graphviz.js, the isMDOrCascadeDelete attr is used to control this. 

Is this the wrong way to know if a relationship is a master detail?

**Comment by austinwang1121** [comment]
I will have a try on this bug

**Comment by stevebuik** [comment]
Certainly, Because I haven't written clear developer onboarding docs yet, you'll probably get stuck setting up. I can't help you do that quickly. Can you let me know when is a good time to have a quick screen-share so I can help you get started?

**Comment by jasong327** [comment]
isMDOrCascadeDelete is populated in controller class GraphVizForceController:
fieldWrapper.isMDOrCascadeDelete = fieldResult.isCascadeDelete();
When we started the original VF version, Schema Namespace does provide MD relationship attribute but only isCascadeDelete. Not sure if recent releases filled the gap or not.

**Comment by austinwang1121** [comment]
Hi Steve, are you OK to have a quick catch up tonight? Maybe 8 pm or 8:30 pm? Or please let me know what's the best time for you. Cheers

**Comment by austinwang1121** [comment]
This turns out to be not a bug. Anyway, I will cover this scenario in the test later. Cheers

![screen shot 2018-06-06 at 3 45 12 pm](https://user-images.githubusercontent.com/4109608/41019142-c49670c2-69a0-11e8-82fa-f0e9005cf75f.png)

**Comment by stevebuik** [comment]
can you check one more thing? in the old tool http://stevebuik.github.io/GraphVizForce/ the relationship between Account and Opportunity is MD. Yet in this tool, it displays as a dashed line.

Maybe there's something extra still to be done here.

**Comment by stevebuik** [comment]
scratch that. I just checked in setup and that relationship is actually a lookup. must have been a bug in the old GVF
