### ISSUE TITLE
Error when using SOQL renderer with Account and Lead objects together

### ISSUE THREAD

**Issue by jasong327** [stevebuik/Graphvizforce-Lightning#54]
Error message:
This page has an error. You might just need to refresh it. Action failed: gvf2:SOQLRenderer$controller$diagramChange [The 'Lead' object cannot be used in a parent -> child relationship query from the 'Account' entity!] Failing descriptor: {gvf2:SOQLRenderer$controller$diagramChange}

Steps to reproduce:
1. Add account object.
2. Choose Account object in SOQL renderer
3. Add Lead Object

Screenshot:
![image](https://user-images.githubusercontent.com/6101374/44315747-8b93ad80-a46a-11e8-96f3-8d9c214e59d9.png)

**Comment by stevebuik** [comment]
fixed by handling the error and clearing the from
