### ISSUE TITLE
Cannot read property 'isCascadeDelete' of undefined

### ISSUE THREAD

**Issue by SaschaWeicht** [stevebuik/Graphvizforce-Lightning#59]
When having Account, Contact, Work Order, Work Order Line Item, Product, Product Consumed, Product Item and Order Product Objects selected and adding the Order-Object this error comes up:

> This page has an error. You might just need to refresh it. Action failed: gvf2:DiagramOutput$controller$onDiagramUpdated [Cannot read property 'isCascadeDelete' of undefined] Failing descriptor: {gvf2:DiagramOutput$controller$onDiagramUpdated}

The error is not gone with a page refresh and even after fresh login to salesforce the error comes up when opening the stored diagram.

When adding Order-Object as the first or second object I was not able to reproduce the issue.

**Comment by SaschaWeicht** [comment]
Duplicate of #58 - Steve was faster to create the issue.

**Comment by stevebuik** [comment]
Thanks Sascha!
